  
export const CHANGE_DISPLAY_INPUT = "CHANGE_DISPLAY_INPUT"

export const GET_EXERCISE_REQUEST = "GET_EXERCISE_REQUEST"
export const GET_EXERCISE_SUCCESS = "GET_EXERCISE_SUCCESS"
export const GET_EXERCISE_SUCCESS2 = "GET_EXERCISE_SUCCESS2"
export const GET_EXERCISE_FAILURE = "GET_EXERCISE_FAILURE"
